// flow-typed signature: 1815d1de0281873baf318f391d1afe8c
// flow-typed version: <<STUB>>/poi-preset-react_v^9.2.1/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'poi-preset-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'poi-preset-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'poi-preset-react/index' {
  declare module.exports: $Exports<'poi-preset-react'>;
}
declare module 'poi-preset-react/index.js' {
  declare module.exports: $Exports<'poi-preset-react'>;
}
