// flow-typed signature: 793f88ff1db78c9e56d30a2c58172e12
// flow-typed version: <<STUB>>/poi_v^9.6.13/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'poi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'poi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'poi/app/postcss.config' {
  declare module.exports: any;
}

declare module 'poi/bin/cli' {
  declare module.exports: any;
}

declare module 'poi/bin/main' {
  declare module.exports: any;
}

declare module 'poi/bin/run' {
  declare module.exports: any;
}

declare module 'poi/lib/app-error' {
  declare module.exports: any;
}

declare module 'poi/lib/create-config' {
  declare module.exports: any;
}

declare module 'poi/lib/handle-options' {
  declare module.exports: any;
}

declare module 'poi/lib/index' {
  declare module.exports: any;
}

declare module 'poi/lib/logger' {
  declare module.exports: any;
}

declare module 'poi/lib/server' {
  declare module.exports: any;
}

declare module 'poi/lib/terminal-utils' {
  declare module.exports: any;
}

declare module 'poi/lib/utils' {
  declare module.exports: any;
}

declare module 'poi/lib/webpack-utils' {
  declare module.exports: any;
}

declare module 'poi/lib/webpack/css-loaders' {
  declare module.exports: any;
}

declare module 'poi/lib/webpack/fancy-log-plugin' {
  declare module.exports: any;
}

declare module 'poi/lib/webpack/handle-errors/index' {
  declare module.exports: any;
}

declare module 'poi/lib/webpack/handle-errors/output' {
  declare module.exports: any;
}

declare module 'poi/lib/webpack/timefix-plugin' {
  declare module.exports: any;
}

declare module 'poi/lib/webpack/transform-js' {
  declare module.exports: any;
}

declare module 'poi/lib/webpack/transform-vue' {
  declare module.exports: any;
}

// Filename aliases
declare module 'poi/app/postcss.config.js' {
  declare module.exports: $Exports<'poi/app/postcss.config'>;
}
declare module 'poi/bin/cli.js' {
  declare module.exports: $Exports<'poi/bin/cli'>;
}
declare module 'poi/bin/main.js' {
  declare module.exports: $Exports<'poi/bin/main'>;
}
declare module 'poi/bin/run.js' {
  declare module.exports: $Exports<'poi/bin/run'>;
}
declare module 'poi/lib/app-error.js' {
  declare module.exports: $Exports<'poi/lib/app-error'>;
}
declare module 'poi/lib/create-config.js' {
  declare module.exports: $Exports<'poi/lib/create-config'>;
}
declare module 'poi/lib/handle-options.js' {
  declare module.exports: $Exports<'poi/lib/handle-options'>;
}
declare module 'poi/lib/index.js' {
  declare module.exports: $Exports<'poi/lib/index'>;
}
declare module 'poi/lib/logger.js' {
  declare module.exports: $Exports<'poi/lib/logger'>;
}
declare module 'poi/lib/server.js' {
  declare module.exports: $Exports<'poi/lib/server'>;
}
declare module 'poi/lib/terminal-utils.js' {
  declare module.exports: $Exports<'poi/lib/terminal-utils'>;
}
declare module 'poi/lib/utils.js' {
  declare module.exports: $Exports<'poi/lib/utils'>;
}
declare module 'poi/lib/webpack-utils.js' {
  declare module.exports: $Exports<'poi/lib/webpack-utils'>;
}
declare module 'poi/lib/webpack/css-loaders.js' {
  declare module.exports: $Exports<'poi/lib/webpack/css-loaders'>;
}
declare module 'poi/lib/webpack/fancy-log-plugin.js' {
  declare module.exports: $Exports<'poi/lib/webpack/fancy-log-plugin'>;
}
declare module 'poi/lib/webpack/handle-errors/index.js' {
  declare module.exports: $Exports<'poi/lib/webpack/handle-errors/index'>;
}
declare module 'poi/lib/webpack/handle-errors/output.js' {
  declare module.exports: $Exports<'poi/lib/webpack/handle-errors/output'>;
}
declare module 'poi/lib/webpack/timefix-plugin.js' {
  declare module.exports: $Exports<'poi/lib/webpack/timefix-plugin'>;
}
declare module 'poi/lib/webpack/transform-js.js' {
  declare module.exports: $Exports<'poi/lib/webpack/transform-js'>;
}
declare module 'poi/lib/webpack/transform-vue.js' {
  declare module.exports: $Exports<'poi/lib/webpack/transform-vue'>;
}
